services:
  mysql-db:
    build: ./mysql-db
    container_name: portfolio-mysql-db
    env_file: 
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    mem_limit: 256m
    restart: unless-stopped

  api:
    build: ./api
    container_name: portfolio-api
    env_file:
      - .env
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    depends_on:
      api:
        condition: service_started
    volumes:
      - /usr/src/app/node_modules
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: portfolio-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
