services:
  mysql-db:
    image: mysql:latest
    container_name: portfolio-mysql-db
    env_file: 
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    restart: always

  api:
    image: ${{ secrets.DOCKER_USERNAME }}/portfolio-api:latest
    container_name: portfolio-api
    env_file:
      - .env
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - ${API_PORT}:${API_PORT}
    restart: always

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest
    container_name: portfolio-frontend
    depends_on:
      api:
        condition: service_started
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    restart: always

  nginx:
    image: nginx:latest
    container_name: portfolio-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - api
      - frontend
    restart: always
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
