services:
  mysql-db:
    build: ./mysql-db
    container_name: portfolio-mysql-db
    env_file: 
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    restart: unless-stopped
  api:
    build: ./api
    container_name: portfolio-api
    env_file:
      - .env
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    restart: unless-stopped
