services:
  mysql-db:
    build: ./mysql-db
    container_name: portfolio-mysql-db
    env_file: 
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    restart: unless-stopped
    
  api:
    build: ./api
    container_name: portfolio-api
    env_file:
      - .env
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - portfolio
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    env_file:
      - ./frontend/.env
    depends_on:
      mysql-db:
        condition: service_healthy
      api:
        condition: service_started
    volumes:
      - /usr/src/app/node_modules
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    networks:
      - portfolio
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - portfolio

networks:
  portfolio:
    driver: bridge
