# .github/workflows/ci-cd-pipeline.yml
name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Copy docker-compose.yml to Droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          source: "docker-compose.prod.yml"
          target: "/root/Portfolio/"

      - name: Copy nginx.prod.conf to Droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          source: "nginx.prod.conf"
          target: "/root/Portfolio/"

      - name: Create a new .env file on Droplet
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          script: |
            rm -f /root/Portfolio/.env
            echo "MYSQL_HOST=${{ vars.MYSQL_HOST }}" >> /root/Portfolio/.env
            echo "MYSQL_ROOT_USER=${{ vars.MYSQL_ROOT_USER }}" >> /root/Portfolio/.env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> /root/Portfolio/.env
            echo "MYSQL_DATABASE=${{ vars.MYSQL_DATABASE }}" >> /root/Portfolio/.env
            echo "MYSQL_PORT=${{ vars.MYSQL_PORT }}" >> /root/Portfolio/.env
            echo "API_PORT=${{ vars.API_PORT }}" >> /root/Portfolio/.env
            echo "CLIENT_PORT=${{ vars.CLIENT_PORT }}" >> /root/Portfolio/.env
            echo "CLIENT_URL=${{ vars.CLIENT_URL }}" >> /root/Portfolio/.env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> /root/Portfolio/.env
            echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> /root/Portfolio/.env
            echo "EMAIL=${{ vars.EMAIL }}" >> /root/Portfolio/.env

      - name: Deploy Docker Containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          script: |
            echo ${{ secrets.DOCKER_PAT }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            cd /root/Portfolio
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
  
      - name: Clean Up Docker Volumes
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          script: |
            docker volume prune -f
