# .github/workflows/ci-cd-pipeline.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Create .env file
        run: |
          echo "MYSQL_HOST=${{ vars.MYSQL_HOST }}" >> .env
          echo "MYSQL_ROOT_USER=${{ vars.MYSQL_ROOT_USER }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ vars.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_PORT=${{ vars.MYSQL_PORT }}" >> .env
          echo "API_PORT=${{ vars.API_PORT }}" >> .env
          echo "NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}" >> .env
          echo "CLIENT_PORT=${{ vars.CLIENT_PORT }}" >> .env
          echo "CLIENT_URL=${{ vars.CLIENT_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env

      - name: Build Docker images
        run: docker-compose build

      - name: Tag Docker image
        run: docker tag portfolio-api:latest ${{ secrets.DOCKER_USERNAME }}/portfolio-api:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-api:latest

      - name: Run Docker Compose
        run: docker-compose up -d

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          script: |
            echo ${{ secrets.DOCKER_PAT }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-api:latest
            docker stop portfolio-api || true
            docker rm portfolio-api || true
            echo "MYSQL_HOST=${{ vars.MYSQL_HOST }}" >> .env
            echo "MYSQL_ROOT_USER=${{ vars.MYSQL_ROOT_USER }}" >> .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
            echo "MYSQL_DATABASE=${{ vars.MYSQL_DATABASE }}" >> .env
            echo "MYSQL_PORT=${{ vars.MYSQL_PORT }}" >> .env
            echo "API_PORT=${{ vars.API_PORT }}" >> .env
            echo "NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}" >> .env
            echo "CLIENT_PORT=${{ vars.CLIENT_PORT }}" >> .env
            echo "CLIENT_URL=${{ vars.CLIENT_URL }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
            docker run -d --name portfolio-api -p 80:80 \
              --env-file .env \
              ${{ secrets.DOCKER_USERNAME }}/portfolio-api:latest